# Generated by Django 2.0.6 on 2020-05-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=100)),
                ('excerpt', models.TextField(max_length=300)),
                ('description', models.TextField()),
                ('num_lesson', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(upload_to='course_picture')),
            ],
        ),
    ]
